import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Box, Button, ButtonGroup, Card, CardBody, CardFooter,Image, Divider, Grid, Heading, Stack, Text } from '@chakra-ui/react'
import Link from 'next/link'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

 function Home({data}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Heading>this is movie page</Heading>
        <Grid gap="10" gridTemplateColumns='repeat(4,1fr)'>

        {data.map((ele,ind)=>(
            <>
            {/* <Link herf={`/movies/{ele.id}`} > */}
            <Card maxW='sm' id={ind}>
  <CardBody>
    <Image
      src={ele.Images[0]}
      alt='Green double couch with wooden legs'
      borderRadius='lg'
    />
    <Stack mt='6' spacing='3'>
      <Heading size='md'>{ele.Title}</Heading>
      <Text>
       {ele.Language}
      </Text>
      <Text color='blue.600' fontSize='2xl'>
       Rating ${ele.imdbRating}
      </Text>
    </Stack>
  </CardBody>
  <Divider />
  <CardFooter>
    <ButtonGroup spacing='2'>
      <Button variant='solid' colorScheme='blue'>
            <Link href={`/${ele.id}`} >

        Click Here
        </Link>
      </Button>
    
    </ButtonGroup>
  </CardFooter>
</Card>
{/* // </Link> */}
            </>
        ))}


     </Grid>




    </Box>
   

    
    </>
  )
}


export default Home

export async function getServerSideProps(context){
  const res=await fetch("http://localhost:8080/movies")
  const data=await res.json()
  return {
      props:{
          data:data
      }
  }
}
